services:
  docker-launchbox:
    build: .
    container_name: docker-launchbox
    ports:
      - "3000:3000"
    volumes:
      - ./config:/config
      - ./games:/games
      - ./installer:/installer
      - ./launchbox:/launchbox
    restart: unless-stopped
